# Generated by Django 4.1.7 on 2023-03-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Is_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Is_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Is_superadmin',
            new_name='is_superadmin',
        ),
    ]
